---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-backend'
  labels:
    app.kubernetes.io/name: bashdoard
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: 1
  selector:
    matchLabels:
      # TODO: Use templates
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: '{{.Values.image.backend.repository}}:{{.Values.image.backend.tag}}'
        ports:
        - containerPort: 8080