---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-frontend'
  labels:
    # TODO: Use templates
    app.kubernetes.io/name: bashdoard
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80