---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ .Release.Name }}-postgres'
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: '{{.Values.persistence.basepath}}-postgres'
    server: '{{.Values.persistence.server}}'
  storageClassName: ""
  claimRef: 
    name: '{{ .Release.Name }}-postgres'
    namespace: {{ .Release.Namespace }}
