---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: '{{ .Release.Name }}-webserver-media'
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi