---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ng-ingressroute
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: 'Host(`{{ .Values.ingress.url }}`)'
      kind: Rule
      services:
        - name: '{{ .Release.Name }}-webserver'
          kind: Service
          port: 8000
  tls:                              
    certResolver: letsencrypt