apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "chart.metadata" . | nindent 2 }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: jmalloc/echo-server
          ports:
            - containerPort: {{ .Values.containerPort }}